language: ruby
before_install:
  - gem update --system
  - gem update bundler
bundler_args: --without benchmark
os:
  - linux
  - osx
env:
  - JARO_WINKLER_PURE_RUBY=
  - JARO_WINKLER_PURE_RUBY=yes
rvm:
  - 2.5.0
  - 2.4.3
  - 2.3.5
  - 2.2.9
  - 2.1.10
  - 2.0.0
  - 1.9.3
  - jruby-19mode
matrix:
  exclude:
    - rvm: 2.0.0
      os: osx
    - rvm: 1.9.3
      os: osx
  include:
    - rvm: 2.0.0
      os: osx
      osx_image: xcode7.3
    - rvm: 1.9.3
      os: osx
      osx_image: xcode7.3
